MainPage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.index, name="index"),

    path('about_us/', views.aboutUs, name="about_us"),

    path('post/<str:slug>/', views.post_detail, name="post_detail_url"),
    path('articles/', views.articles, name="articles"),

    path('courses/', views.courses, name="courses"),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/reset_password/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/reset_password/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/reset_password/password_reset_form.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/reset_password/password_reset_done.html"),
         name="password_reset_complete"),

    path('user/', views.userPage, name="user-page"),
    path('account/', views.accountSettings, name="account"),

]

MathLegend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from prompt_toolkit import document

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainPage.urls')),
    path('tinymce/', include('tinymce.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainPage/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from tinymce.models import HTMLField


class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    preview_text = models.CharField(max_length=150)
    text = HTMLField()
    date_pub = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=150, unique=True)
    preview_image = models.ImageField(upload_to='static/img')

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})  # это называется url-реверсинг

    def __str__(self):
        return '{}'.format(self.title)


class Player(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    profile_pic = models.ImageField(default="android.png", null=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = HTMLField()
    create = models.DateTimeField(auto_now_add=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

MainPage/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ('name', 'email', 'profile_pic')
        exclude = ['players']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите здесь свой псевдоним'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'})
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        def __init__(self, *args, **kwargs):
            super(CommentForm, self).__init__(*args, **kwargs)
            self.fields['text'].widget.attrs.update({'class': 'form-control'})

MainPage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import Group
from .decorators import unauthenticated_user, allowed_users, admin_only
from .models import Post, Player, Comment
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm, PlayerForm, CommentForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'Имя пользователя или пароль введены некорректно')

    context = {}
    return render(request, 'accounts/login/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')


@unauthenticated_user
def registerPage(request):
    form = CreateUserForm
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + username)

            return redirect('login')

    context = {'form': form}
    return render(request, 'accounts/registration/register.html', context)


def index(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return redirect('index')
    else:
        messages.info(request, 'Username or password is incorrect')

    return render(
        request,
        'main_pages/index.html',
        {
        }
    )


def aboutUs(request):
    return render(
        request,
        'about_us/aboutUs.html',
        {
        }
    )


def articles(request):
    posts = Post.objects.all()
    return render(request, 'articles/articles.html', context={'posts': posts})


def post_detail(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    comments = Comment.objects.filter(post=post).order_by('-id')
    if request.method=='POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            text = request.POST.get('text')
            comment = Comment.objects.create(post=post, user=request.user, text=text)
            comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()
    return render(request, 'articles/post_detail/post_detail.html', context={'post': post,
                                                                             'comments': comments,
                                                                             'comment_form': comment_form})


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='login')
def courses(request):
    return render(request, 'course/course.html')


@allowed_users(allowed_roles=['players'])
@login_required(login_url='login')
def userPage(request):
    context = {}
    return render(request, 'accounts/users/user.html', context)


@login_required(login_url='login')
def accountSettings(request):
    player = request.user.player
    form = PlayerForm(instance=player)

    if request.method == 'POST':
        form = PlayerForm(request.POST, request.FILES, instance=player)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'accounts/users/account_settings.html', context)

MainPage/templates/about_us/aboutUs.html
{% extends "base.html" %}
{% block title %}About_us{% endblock %}
{% block content %}


{% endblock %}

MainPage/templates/accounts/login/login.html
{% extends 'base.html' %}
{% block content %}
    <style type="text/css">
    	body,
		html {
			height: 100%;
			background-image: url("/static/img/graham-w-sketch-41-greyscale.jpg");
            background-repeat: no-repeat;
            background-position: center center;
            background-attachment: fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: rgba(0, 0, 5, 0.68);
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		.sign-wrap-1 {
    text-align: center;
}
.sign-wrap-1 .sign_word {
    font-size: 24px;
    font-family: 'Jura', serif;
    font-weight: bold;
    color: #FFF;
    text-transform: uppercase;
    animation: neon-1 .1s ease-in-out infinite alternate;
}
@keyframes neon-1 {
    from {
        text-shadow: 0 0 6px rgba(202, 228, 225, 0.92), 0 0 30px rgba(202, 228, 225, 0.34), 0 0 12px rgba(191, 226, 255, 0.52), 0 0 21px rgba(191, 226, 255, 0.92), 0 0 34px rgba(191, 226, 255, 0.78), 0 0 54px rgba(191, 226, 255, 0.92);
    }
    to {
        text-shadow: 0 0 6px rgba(202, 228, 225, 0.98), 0 0 30px rgba(202, 228, 225, 0.42), 0 0 12px rgba(191, 226, 255, 0.58), 0 0 22px rgba(191, 226, 255, 0.84), 0 0 38px rgba(191, 226, 255, 0.88), 0 0 60px #FFF;
    }
}

		.login_btn {
            font-family: 'Jura', serif;
            font-size: 15px;
			color: #ece9ee !important;
            border: 2px solid transparent;
            border-image: linear-gradient( 135deg, #ffffff 10%, #acacac 100%);
            -moz-border-image: -moz-linear-gradient( 135deg, #ffffff 10%, #acacac 100%);
            -webkit-border-image: -webkit-linear-gradient( 135deg, #ffffff 10%, #acacac 100%);
            border-image-slice: 1;
            border-radius: 50%;

		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background-image: linear-gradient(135deg, #ffffff 10%, #acacac 100%); !important;
			color: #ece9ee !important;
			border: 0 !important;
			border-radius: 2px 0px 0px 2px !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			font-family: 'Jura', serif;
            font-size: 15px;
            color: #ffffff;
            text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
            padding: 10px;
			margin-top: 10px;
		}
        .ml-2{
            color: #ffffff;
            font-family: 'Jura', serif;
            font-size: 15px;

        }
        .ml-2:hover{
            text-decoration: none;
            color: #acacac;


        }
        .links{
            font-family: 'Jura', serif;
            background: linear-gradient(135deg, #ffffff 10%, #acacac 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            color: #ffffff;
            font-size: 15px;
        }

        .ml-3{
            color: #ffffff;
            font-family: 'Jura', serif;
            font-size: 15px;
        }

        .ml-3:hover{
            text-decoration: none;
            color: #acacac;
        }

        .click{
            background: linear-gradient(135deg, #ffffff 10%, #acacac 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            color: white;
            font-family: 'Jura', serif;
            font-size: 15px;
        }

        .form-control{
            background: rgba(0,0,5,0);
            font-family: 'Jura', serif;
        }
        


    </style>
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="sign-wrap-1">
                    <span class="sign_word">ВХОД</span>
                </div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><img src="/static/ico/artificial-intelligence.png" alt="" width="20px" height="20px"></span>
							</div>
							<input type="text" name="username" placeholder="Username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><img src="/static/ico/security(1).png" alt="" width="20px" height="20px"></span>
							</div>
								<input type="password" name="password" placeholder="Password" class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn btn1 btn-outline-light" type="submit" value="Начать">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center">
						<div class="links">У вас нет аккаунта?</div> <a href="{% url 'register' %}" class="ml-2">Регистрация</a>
					</div>
				</div>
            <div class="mt-4">
                <div class="d-flex justify-content-center">
                    <div class="click">Забыли пароль?</div><a href="{% url "reset_password" %}" class="ml-3">Новый пароль</a>
                </div>
            </div>
			</div>
		</div>
	</div>
{% endblock %}

MainPage/templates/accounts/reset_password/password_reset.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">

    .main-block{
        text-align: center;
        padding-top: 17%;
        color: white;
        font-family: 'Jura', serif;
        letter-spacing: 2px;


    }
    body{
        background-image: url("/static/img/d29.resizedimage.jpg");
        background-repeat: no-repeat;
        background-position: center center;
        background-attachment: fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }

    h1.reset {
        font-size: 33px;
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;

    }
    p.reset {
        font-size: 17px;

    }
    .reset-block{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        font-size: 20px;
    }

    .btn{
        margin-top: 10px;
        transition: 0.5s;
        margin-left: 5px;

    }

    .btn:hover{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        background: rgba(0,0,5,0);
    }
    .form-control{
        margin-top: 10px;
        max-width: 300px;
        background: rgba(0,0,5,0);
        color: #FFFFFF;
    }

    .reset-block{

    }



</style>
<div class="container main-block">
<h1 class="reset">Сброс пароля</h1>
<p class="reset">Вы забыли свой пароль? Введите свой адрес электронной почты и мы вышлем вам инструкцию по созданию нового пароля</p>
    <form method="post" class="">
        {% csrf_token %}
        <div class="row justify-content-center reset-block">
            <input type="text" name="email" class="form-control" id="id_form">
            <input type="Submit" name="Send email" class="btn btn-outline-light" value="Отправить">
        </div>
    </form>
</div>
{% endblock %}

MainPage/templates/accounts/reset_password/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">

    .main-block{
        text-align: center;
        padding-top: 4%;
        color: white;
        font-family: 'Jura', serif;
        letter-spacing: 2px;
        margin-bottom: 300px;

    }
    body{
        background: #000005;
    }

    h1.done{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        font-size: 30px;

    }
    .btn{
            margin-top: 10px;
            transition: 0.5s;
            margin-left: 5px;

        }

    .btn:hover{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        background: rgba(0,0,5,0);
    }




</style>
<div class="container main-block">
    <h1 class="done">Пароль установлен</h1>

    <p>Ваш пароль был успешно сменён. Сейчас вы можете войти в аккаунт.</p>

    <a href="{% url "login" %}" class="btn btn-outline-light">Войти</a>
</div>
{% endblock %}

MainPage/templates/accounts/reset_password/password_reset_form.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">

    .main-block{
        text-align: center;
        padding-top: 4%;
        color: white;
        font-family: 'Jura', serif;
        letter-spacing: 2px;
        margin-bottom: 300px;

    }
    body{
        background: #000005;
    }

    h1.enter{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        font-size: 30px;

    }

    .enter-form{

        margin-top: 30px;
    }

    #id_form{
        background: rgba(173,241,255,0);
    }
    .btn{

            transition: 0.5s;
            margin-left: 5px;

        }

    .btn:hover{
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;
        background: rgba(0,0,5,0);
    }


</style>
<div class="container main-block">
    <h1 class="enter">Введите новый пароль</h1>
    <form method="post">
        {% csrf_token %}
        <div class="enter-form">
        {{ form }}
        <input type="Submit" name="Update Password" class="btn btn-outline-light" value="Обновить">
            </div>
    </form>
</div>
{% endblock %}

MainPage/templates/accounts/reset_password/password_reset_sent.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">

    .main-block{
        text-align: center;
        padding-top: 17%;
        color: white;
        font-family: 'Jura', serif;
        letter-spacing: 2px;

    }
    body{
        background-image: url("/static/img/d29.resizedimage.jpg");
        background-repeat: no-repeat;
        background-position: center center;
        background-attachment: fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }

    h1.sent{
        font-size: 33px;
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;

    }

    p.sent {
        font-size: 17px;

    }


</style>
<div class="container main-block">
    <h1 class="sent">Сообщение отправленно</h1>
    <p class="sent">пожалуйста проверьте свою почту</p>
</div>
{% endblock %}

MainPage/templates/accounts/users/account_settings.html
{% extends "base.html" %}
{% block content %}
<style>
    body{
    height: 100%;
    background-image: url("/static/img/graham-w-sketch-41-greyscale.jpg");
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    }
    .profile-pic{
    margin: 0 auto;
    object-fit: cover;
    width: 300px;
    height: 300px;
    border-radius: 50%;
    }
    .user_card {
    width: 700px;
    height: 730px;
    margin-top: auto;
    margin-bottom: auto;
    background: rgba(0, 0, 5, 0.68);
    position: relative;
    display: flex;
    justify-content: center;
    flex-direction: column;
    padding: 10px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 8px;
    }
    .container {
    margin-top: 80px;
    }
    .input-settings{
    }
    .form-group{
    margin-top: 20px;
    }
    .settings{
    color: white;
    }
    .change-btn{

        transition: 1s;
    }
    .change-btn:hover{

        border-color: #FFFFFF;
        color: #FFFFFF;
        background-color: rgba(250, 235, 215, 0);
    }
    h4{
        font-family: 'Jura', serif;
        color: #ffffff;
        text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #FFFFFF, 0 0 80px #FFFFFF, 0 0 90px #FFFFFF, 0 0 100px #FFFFFF, 0 0 150px #FFFFFF;

    }
    h1.yellow {

    }
    .input-email{
        margin-top: 20px;


    }
    .input-name{
        margin-top: 30px;

    }
    #id_name{
        font-size: large;
        font-family: 'Jura', serif;
        background: rgba(105,98,104,0.0);
        color: #FFFFFF;

    }
    #id_email{
        font-size: large;
        font-family: 'Jura', serif;
        background: rgba(105,98,104,0.0);
        color: #FFFFFF;

        }
    .sign-wrap-4 .sign_word {
        font-size: 40px;
        color: #FFF;
        font-family: 'Jura', serif;
        font-weight: normal;
        letter-spacing: 4px;
        text-transform: uppercase;
        text-shadow: 0 -40px 100px, 0 0 2px, 0 0 1em #FFFFFF, 0 0 0.5em #FFFFFF, 0 0 0.1em #FFFFFF;
    }
    .sign-wrap-4 .sign_word span {
        animation: neon-4 linear infinite 2s;
    }
    @keyframes neon-4 {
        78% {
            color: inherit;
            text-shadow: inherit;
        }
        79%{
            color: #0b3960;
        }
        80% {
            text-shadow: none;
        }
        81% {
            color: inherit;
            text-shadow: inherit;
        }
        82% {
            color: #0b3960;
            text-shadow: none;
        }
        83% {
            color: inherit;
            text-shadow: inherit;
        }
        92% {
            color: #0b3960;
            text-shadow: none;
        }
        92.5% {
            color: inherit;
            text-shadow: inherit;
        }
    }

    .form_container{
        padding-top: 20px;
    }
    .btn-avatar{
        transition: 1s;
    }


</style>
</div>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <div class="sign-wrap-4">
                    <div class="sign_word">Н<span>ас</span>т<span>ро</span>й<span>ка</span></div>
                </div>
            </div>
            <div class="d-flex justify-content-center form_container">
                <div class="row">
                    <div class="col-12">
                        <img class="profile-pic" src="{{ request.user.player.profile_pic.url }}">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="input-settings">
                                <div class="input-name">
                                    <h4>name: </h4>
                                    {{ form.name }}
                                </div>
                                <div class="input-email">
                                    <h4>email: </h4>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="id_profile_pic" class='btn btn-outline-light btn-avatar'>Изменить аватар</label>
                                    <input type="file" name="profile_pic" id="id_profile_pic" style='display:none'>
                                </div>
                            </div>
                            <div class="col-6" style="margin: 0 auto">
                                <input class="btn btn-outline-dark change-btn" type="submit" name="Update Information" value="Внести изменения">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MainPage/templates/accounts/users/user.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

MainPage/templates/articles/articles.html
{% extends "base.html" %}
{% block title %}Articles{% endblock %}
{% block content %}
<style type="text/css">
body {
    height: 100%;
    background-image: url("/static/img/rpo.jpg");
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;

}

.card-deck{
    margin-top: 20px;
}
.card{
    margin-top: 20px;
}

</style>


<div class="card-deck">
   {% for post in posts %}
       <div class="col-xl-3">
      <div class="card">
         <a href="{{ post.get_absolute_url }}">
         <img class="card-img-top" src="/{{ post.preview_image }}" alt="Card image cap" width="auto" height="200px">
         </a>
         <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.preview_text }}</p>
            <p class="date">{{ post.date_pub }}</p>
         </div>
      </div>
</div>
   {% endfor %}
 </div>

{% endblock %}

MainPage/templates/course/course.html
{% extends "base.html" %}
{% block title %}Course{% endblock %}
{% block content%}
    <div class="container">
    <div class="col-12" style="text-align: center; margin-top: 400px; margin-bottom: 400px">
    <div class="sign-wrap-3">
        <span class="sign_word" style="font-size: 50px">Copyright courses will appear here soon</span>
    </div>
</div>
    </div>
{% endblock %}